import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/Components/Navbar';
import Footer from '@/Components/Footer';
import { ToastContainer } from 'react-toastify';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  flex flex-col min-h-screen`}
      >
        <nav>
          <Navbar />
        </nav>
        <main className="flex-grow">
          {children}
          <ToastContainer position="top-center" />
        </main>

        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
